version: "2"

plugins:
  brakeman: 
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 20
  rubocop:
    enabled: false
    channel: rubocop-0-83

  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - TODO
        - JTPTODO
        - SPECME
      issue_override:
        severity: info

exclude_patterns:
  - "bin/**"
  - "spec/**"
