language: ruby
rvm:
  - "2.2.10"
  - "2.3.8"
  - "2.4.9"
  - "2.5.7"
  - "2.6.5"
gemfile:
  - Gemfile
  - spec/support/Gemfile.rails5.2
  - spec/support/Gemfile.rails5.1
  - spec/support/Gemfile.rails5
matrix:
  allow_failures:
    - rvm: "2.2.10"
      gemfile: Gemfile
    - rvm: "2.3.8"
      gemfile: Gemfile
    - rvm: "2.4.9"
      gemfile: Gemfile

before_install:
  - command -v bundle || gem install bundler

script:
  - bundle exec rake
